[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test/foundry"
cache_path = "forge-cache"
evm_version = "shanghai"
# solc = "0.8.25"


[rpc_endpoints]
# arbitrum = "${ARBITRUM}"
ethereum = "${ETHEREUM}"
